spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myapp
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG

#環境変数から値を取得
api:
  base-url: ${API_BASE_URL}
  uploaded-url: ${IMAGE_UPLOADED_URL}


#spring:
#  datasource:
#    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?useSSL=false&serverTimezone=Asia/Tokyo
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver