spring:
  datasource:
    url: jdbc:mysql://${database_endpoint}:3306/${database_name}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Tokyo
    username: ${database_username}
    password: ${database_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  config:
    import:
    - aws-secretsmanager:4471yu4471-image-application/s3/MySQL/jwt

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG

api:
  base-url: ${API_BASE_URL}
  uploaded-url: ${IMAGE_UPLOADED_URL}
  s3:
    bucket-name: ${s3_bucket_name}
  cloudfront:
    url: ${CLOUDFRONT_URL}

jwt:
  secret-key: ${jwt-secret-key}

#小文字はSecret Managerから値を取得するもの

#spring:
#  datasource:
#    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Tokyo
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  profiles:
#    active: dev


# spring:
#   datasource:
#     url: ${DB_URL}
#     username: ${DB_USERNAME}
#     password: ${DB_PASSWORD}
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   profiles:
#     active: dev
#   config:
#     import:
#     - aws-secretsmanager:4471yu4471-image-application/s3/MySQL/jwt